# -*- coding: utf-8 -*-
"""question 2 labreprt 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ygVrS-CJ2TrLtDwsdgjMg5HQPumKX1h
"""

from IPython.display import Image
Image("/content/LabReport_BSD2513_#1.jpg")

from collections import deque

# Graph adjacency list based on your image
graph = {
    'A': ['B', 'D'],
    'B': ['C', 'E', 'G'],
    'C': ['D'],
    'D': ['A'],
    'E': ['H'],
    'F': [],
    'G': ['F', 'H'],
    'H': []
}

# Breadth-First Search (BFS) with alphabetical ordering
def bfs(start):
    visited = set()
    queue = deque([start])
    order = []

    while queue:
        node = queue.popleft()
        if node not in visited:
            visited.add(node)
            order.append(node)
            # Add neighbors in alphabetical order to queue
            for neighbor in sorted(graph[node]):
                if neighbor not in visited:
                    queue.append(neighbor)
    return order

# Depth-First Search (DFS) with alphabetical ordering
def dfs(start):
    visited = set()
    stack = [start]
    order = []

    while stack:
        node = stack.pop()
        if node not in visited:
            visited.add(node)
            order.append(node)
            # Add neighbors in reverse alphabetical order so smallest is popped first
            for neighbor in sorted(graph[node], reverse=True):
                if neighbor not in visited:
                    stack.append(neighbor)
    return order

# Run the searches starting from 'A'
bfs_order = bfs('A')
dfs_order = dfs('A')

print("BFS Order:", bfs_order)
print("DFS Order:", dfs_order)